### ISSUE TITLE
[Bug] BBD does not work with BeautifulDiscord

### ISSUE THREAD

**Issue by sapphonie** [rauenzi/BetterDiscordApp#459]
**Describe the Bug**
I used to be able to run BDD and [BeautifulDiscord](https://github.com/leovoel/BeautifulDiscord) at the same time. This is no longer the case, as injecting BeautifulDiscord effectively uninstalls BBD.

**To Reproduce**
Install BBD
Install [BeautifulDiscord](https://github.com/leovoel/BeautifulDiscord)
Open Discord
Inject BeautifuldDiscord
BBD does not function properly, even after a repair or reinstall of BBD

**Expected Behavior**
BeautifulDiscord and BBD would work at the same time. They do not

**Discord Version**
Stable 68015 (1f4ca13)
Windows 10 64-Bit (10.0.18362)

**Comment by rauenzi** [comment]
They are not intended to work together, and I will not add support to do so. There is no reason to have both installed.

**Comment by sapphonie** [comment]
There definitely is reason to have both installed, the bbd css editor is a complete trash fire to use lol

**Comment by rauenzi** [comment]
You can use your own editor with BD as well, you just put it in a theme file instead of the custom css editor.

**Comment by rauenzi** [comment]
As an example, you can create a file called `zCustomCSS.theme.css` (note the `z` in front because BD loads them in alphabetical order in case you want to override styles from other themes). Then you can open it with any editor of your choosing and put something like this:
```css
/**
 * @name My Custom CSS
 * @author sapphonie
 * @version 1.0.0
 * @description My custom css in my own editor
 */
 
:root {
    --accent-color: #ff6875;
}
```
