### ISSUE TITLE
[Bug] Minimal Mode Stage Discovery tab

### ISSUE THREAD

**Issue by dav1312** [rauenzi/BetterDiscordApp#847]
**Describe the Bug**
The new Stage Discovery tab doesn't have the same style as the other tabs

**To Reproduce**
Enable minimal mode

**Expected Behavior**
Same style as the other tabs
![image](https://user-images.githubusercontent.com/63931154/123423075-60891b00-d5bf-11eb-9efd-1ea168fe47cf.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/63931154/123422690-da6cd480-d5be-11eb-80e7-faa9949e0524.png)

**Discord Version**
All

**Comment by dav1312** [comment]
```css
/* Private channels horizontal icons */

.bd-minimal .channel-2QD9_O[href="/channels/@me"],
.bd-minimal .channel-2QD9_O[href="/discovery"],
.bd-minimal .channel-2QD9_O[href="/library"],
.bd-minimal .channel-2QD9_O[href="/store"] {
    width: calc(25% - 8px);
    margin-left: 8px;
    padding: 0;
    display: inline-block;
}

.bd-minimal .channel-2QD9_O[href="/channels/@me"] .content-3QAtGj,
.bd-minimal .channel-2QD9_O[href="/discovery"] .content-3QAtGj,
.bd-minimal .channel-2QD9_O[href="/library"] .content-3QAtGj,
.bd-minimal .channel-2QD9_O[href="/store"] .content-3QAtGj,
.bd-minimal .channel-2QD9_O[href="/channels/@me"] .children-gzQq2t,
.bd-minimal .channel-2QD9_O[href="/discovery"] .children-gzQq2t,
.bd-minimal .channel-2QD9_O[href="/library"] .children-gzQq2t,
.bd-minimal .channel-2QD9_O[href="/store"] .children-gzQq2t {
    display: none;
}

.bd-minimal .channel-2QD9_O[href="/channels/@me"] .avatar-3uk_u9,
.bd-minimal .channel-2QD9_O[href="/discovery"] .avatar-3uk_u9,
.bd-minimal .channel-2QD9_O[href="/library"] .avatar-3uk_u9,
.bd-minimal .channel-2QD9_O[href="/store"] .avatar-3uk_u9 {
    margin: 0;
    flex-grow: 1;
}

.bd-minimal .layout-2DM8Md {
    justify-content: center;
}
```
